SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [ETL_TEMP].[INSERT_COBORROWER_ALLSOURCE]
AS

BEGIN

/*TRUNCATION OF PREVIOUD DAY DATA FOR ALL_SOURCE_STG_DAILY*/

TRUNCATE TABLE IBL_ENPA_TEMPDB_V2.DBO.TEMPCOBORROWER_ALLSOURCE

/*INSERTING STG DAILY FROM ALL SOURCE SYSTEM*/

/*SELECT * INTO TEMPCOBORROWER_ALLSOURCE FROM IBL_ENPA_STGDB_V2.DBO.MERGE_COBORROWER WHERE 1=2*/

INSERT INTO TEMPCOBORROWER_ALLSOURCE(
							AS_ON_DATE
							,ENT_CIF
							,SOURCE
							,SRC_CIF
							,ACC_NO
							,COBO_ENT_CIF
							)
				SELECT AS_ON_DATE
				,ENT_CIF
				,SOURCE
				,SRC_CIF
				,ACC_NO
				,COBO_ENT_CIF 
	FROM IBL_ENPA_STGDB_V2.DBO.MERGE_COBORROWER 
END
GO