CREATE TABLE [dbo].[TempAdVAcBalanceDetail] (
  [EntityKey] [bigint] NULL,
  [AssetClassAlt_Key] [smallint] NULL,
  [BalanceInCurrency] [decimal](16, 2) NULL,
  [Balance] [decimal](16, 2) NULL,
  [SignBalance] [decimal](16, 2) NULL,
  [LastCrDt] [date] NULL,
  [OverDue] [decimal](16, 2) NULL,
  [TotalProv] [decimal](16, 2) NULL,
  [RefCustomerId] [varchar](20) NULL,
  [RefSystemAcId] [varchar](30) NULL,
  [AuthorisationStatus] [char](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [OverDueSinceDt] [date] NULL,
  [MocStatus] [char](1) NULL,
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [Old_OverDueSinceDt] [date] NULL,
  [Old_OverDue] [decimal](16, 2) NULL,
  [ORG_TotalProv] [decimal](16, 2) NULL,
  [IntReverseAmt] [decimal](16, 2) NULL,
  [UnAppliedIntAmount] [decimal](18, 2) NULL,
  [PS_Balance] [decimal](16, 2) NULL,
  [NPS_Balance] [decimal](16, 2) NULL,
  [DateCreated] [date] NULL,
  [ModifiedBy] [varchar](50) NULL,
  [DateModified] [date] NULL,
  [ApprovedBy] [varchar](50) NULL,
  [DateApproved] [date] NULL,
  [CreatedBy] [varchar](50) NULL,
  [UpgradeDate] [date] NULL,
  [OverduePrincipal] [decimal](18, 2) NULL,
  [NotionalInttAmt] [decimal](16, 2) NULL,
  [PrincipalBalance] [decimal](18, 2) NULL,
  [Overdueinterest] [decimal](16, 2) NULL,
  [AdvanceRecovery] [decimal](16, 2) NULL,
  [PS_NPS_FLAG] [varchar](3) NULL,
  [Ischanged] [char](1) NULL,
  [DFVAmt] [decimal](18, 2) NULL,
  [InterestReceivable] [decimal](18, 2) NULL,
  [OverduePrincipalDt] [date] NULL,
  [OverdueIntDt] [date] NULL,
  [OverOtherdue] [decimal](18, 2) NULL,
  [OverdueOtherDt] [date] NULL,
  [SourceAssetClass] [varchar](100) NULL,
  [SourceNpaDate] [smalldatetime] NULL,
  [DPD_Bank] [int] NULL,
  [ACCOUNTENTITYID] [int] IDENTITY
)
ON [PRIMARY]
GO