CREATE TABLE [dbo].[TempAdvAcFinancialDetail] (
  [ENTITYKEY] [bigint] NULL,
  [AccountEntityId] [int] NOT NULL,
  [Ac_LastReviewDueDt] [date] NULL,
  [Ac_ReviewTypeAlt_key] [smallint] NULL,
  [Ac_ReviewDt] [date] NULL,
  [Ac_ReviewAuthAlt_Key] [smallint] NULL,
  [Ac_NextReviewDueDt] [date] NULL,
  [DrawingPower] [decimal](14) NULL,
  [InttRate] [decimal](4, 2) NULL,
  [NpaDt] [date] NULL,
  [BookDebts] [decimal](14) NULL,
  [UnDrawnAmt] [decimal](14) NULL,
  [UnAdjSubSidy] [decimal](14) NULL,
  [LastInttRealiseDt] [date] NULL,
  [MocStatus] [varchar](10) NULL,
  [MOCReason] [smallint] NULL,
  [LimitDisbursed] [decimal](14) NULL,
  [RefCustomerId] [varchar](20) NULL,
  [RefSystemAcId] [varchar](30) NULL,
  [AuthorisationStatus] [char](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [CropDuration] [smallint] NULL,
  [Ac_ReviewAuthLevelAlt_Key] [smallint] NULL,
  [Ischanged] [char](1) NULL,
  [Interest_due] [decimal](16, 2) NULL,
  [other_dues] [decimal](16, 2) NULL,
  [penal_due] [decimal](16, 2) NULL,
  [int_receivable_adv] [decimal](16, 2) NULL,
  [penal_int_receivable] [decimal](16, 2) NULL,
  [Accrued_interest] [decimal](16, 2) NULL
)
ON [PRIMARY]
GO