CREATE TABLE [dbo].[TempAdvNFAcFinancialDetail] (
  [EntityKey] [int] NULL,
  [Ac_ReviewTypeAlt_key] [smallint] NULL,
  [Ac_ReviewAuthAlt_Key] [smallint] NULL,
  [BalanceInCurrency] [decimal](16, 4) NULL,
  [Balance] [decimal](16, 2) NULL,
  [SignBalance] [decimal](16, 2) NULL,
  [OverDue] [decimal](14) NULL,
  [UnDrawnAmt] [decimal](10) NULL,
  [ProvSecured] [decimal](14) NULL,
  [ProvUnSecured] [decimal](14) NULL,
  [AdditionalProv] [decimal](14) NULL,
  [TotalProv] [decimal](14) NULL,
  [SecTangAst] [decimal](14) NULL,
  [CoverGovGur] [decimal](14) NULL,
  [Unsecured] [decimal](14) NULL,
  [RefCustomerId] [varchar](50) NULL,
  [RefSystemAcId] [varchar](30) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [MocDate] [smalldatetime] NULL,
  [MocStatus] [char](1) NULL,
  [MocTypeAlt_Key] [int] NULL,
  [Ac_ReviewAuthLevelAlt_Key] [smallint] NULL,
  [IsChanged] [char](1) NULL,
  [Ac_NextReviewDueDt] [date] NULL,
  [DrawingPower] [decimal](14) NULL,
  [InttRate] [decimal](4, 2) NULL,
  [NpaDt] [date] NULL,
  [CUSTOMERENTITYID] [int] IDENTITY,
  [AccountEntityId] [int] NULL
)
ON [PRIMARY]
GO