CREATE TABLE [dbo].[TempAdvCustOtherDetail_BKP_20250407] (
  [EntityKey] [bigint] NULL,
  [CustomerEntityId] [int] NOT NULL,
  [OrgCostOfEquip] [decimal](16, 2) NULL,
  [OrgCostOfPlantMech] [decimal](16, 2) NULL,
  [DepValPlant] [decimal](16, 2) NULL,
  [ValLand] [decimal](16, 2) NULL,
  [IECDno] [varchar](20) NULL,
  [GroupAlt_Key] [smallint] NULL,
  [CustomerSwiftCode] [varchar](20) NULL,
  [SplCatg1Alt_Key] [smallint] NULL,
  [SplCatg2Alt_Key] [smallint] NULL,
  [SplCatg3Alt_Key] [smallint] NULL,
  [SplCatg4Alt_Key] [smallint] NULL,
  [CmaEligible] [varchar](1) NULL,
  [PFNo] [varchar](10) NULL,
  [SupperAnnuationBenefit] [decimal](16, 2) NULL,
  [SupperannuationBenefitValuationDt] [datetime] NULL,
  [BusinessCommenceDt] [datetime] NULL,
  [CancelObtained] [varchar](1) NULL,
  [TotConsortiumLimitFunded] [decimal](16, 2) NULL,
  [TotConsortiumLimitNonFunded] [decimal](16, 2) NULL,
  [UpgradationDate] [datetime] NULL,
  [CustomerExpiredYN] [char](1) NULL,
  [TotWCLimitFunded] [decimal](16, 2) NULL,
  [Flagged_SubSector] [varchar](1) NULL,
  [RefCustomerId] [varchar](20) NULL,
  [AuthorisationStatus] [char](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [MocStatus] [char](1) NULL,
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [AnnualExportTurnover] [decimal](16, 2) NULL,
  [FMCNumber] [varchar](20) NULL,
  [IsEmployee] [char](1) NULL,
  [IsPetitioner] [char](1) NULL,
  [UnderLitigation] [char](1) NULL,
  [PermiNatureID] [varchar](50) NULL,
  [BorrUnitFunct] [varchar](50) NULL,
  [DtofClosure] [date] NULL,
  [NonCoopBorrower] [varchar](2) NULL,
  [ArbiAgreement] [varchar](2) NULL,
  [TransThroughUs] [varchar](2) NULL,
  [CutBackArrangement] [varchar](2) NULL,
  [BankingArrangement] [varchar](2) NULL,
  [MemberBanksNo] [smallint] NULL,
  [TotalConsortiumAmt] [decimal](16, 2) NULL,
  [ROC_CFCReportDate] [date] NULL,
  [ROC_ChargeFV] [varchar](2) NULL,
  [ROC_ChargeFVDt] [date] NULL,
  [ROC_ChargeRemark] [varchar](1000) NULL,
  [ROC_Securities] [varchar](1000) NULL,
  [ROC_Cover] [varchar](2) NULL,
  [ROC_CoveredDt] [datetime] NULL,
  [ChargeFiledWith] [varchar](2) NULL,
  [FiledDt] [date] NULL,
  [EmployeeID] [varchar](50) NULL,
  [EmployeeType] [varchar](50) NULL,
  [Designation] [nvarchar](50) NULL,
  [Placeofposting] [nvarchar](50) NULL,
  [LPersonalConDate] [date] NULL,
  [LPersonalConDtls] [varchar](1000) NULL,
  [RecallNoticeDate] [date] NULL,
  [RecallNoticeModeID] [varchar](50) NULL,
  [LegalAuditDate] [date] NULL,
  [IrregularityPending] [varchar](2) NULL,
  [IrregularityRectiDate] [date] NULL,
  [FraudAccoStatus] [char](1) NULL,
  [PreSARFAESINoticeDt] [datetime] NULL,
  [FMRNO] [varchar](50) NULL,
  [FMRDate] [datetime] NULL,
  [GradeScaleAlt_Key] [smallint] NULL,
  [FraudNatureRemark] [varchar](1000) NULL,
  [ROCCoveredCertificateRemark] [varchar](1000) NULL,
  [ReasonsNonCoOperativeBorrower] [varchar](500) NULL,
  [StatusNonCoOperativeBorrower] [varchar](500) NULL,
  [Ischanged] [char](1) NULL
)
ON [PRIMARY]
GO