CREATE TABLE [dbo].[TempCustomerBasicDetail_BKP_20250407] (
  [Customer_Key] [bigint] NULL,
  [CustomerEntityId] [int] NOT NULL,
  [CustomerId] [varchar](20) NOT NULL,
  [D2kCustomerid] [varchar](20) NULL,
  [UCIF_ID] [varchar](30) NULL,
  [UcifEntityID] [int] NULL,
  [ParentBranchCode] [varchar](10) NULL,
  [CustomerName] [varchar](100) NULL,
  [CustomerInitial] [varchar](5) NULL,
  [CustomerSinceDt] [date] NULL,
  [ConstitutionAlt_Key] [smallint] NULL,
  [OccupationAlt_Key] [smallint] NULL,
  [ReligionAlt_Key] [smallint] NULL,
  [CasteAlt_Key] [smallint] NULL,
  [FarmerCatAlt_Key] [smallint] NULL,
  [GaurdianSalutationAlt_Key] [smallint] NULL,
  [GaurdianName] [varchar](30) NULL,
  [GuardianType] [smallint] NULL,
  [CustSalutationAlt_Key] [smallint] NULL,
  [MaritalStatusAlt_Key] [smallint] NULL,
  [AssetClass] [varchar](20) NULL,
  [BIITransactionCode] [bit] NULL,
  [D2K_REF_NO] [varchar](15) NULL,
  [ScrCrError] [varchar](100) NULL,
  [ReferenceAcNo] [varchar](10) NULL,
  [CustCRM_RatingAlt_Key] [smallint] NULL,
  [CustCRM_RatingDt] [date] NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [FLAG] [varchar](10) NULL,
  [MocStatus] [char](1) NULL,
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [smallint] NULL,
  [CommonMocTypeAlt_Key] [smallint] NULL,
  [LandHolding] [decimal](16, 2) NULL,
  [ScrCrErrorSeq] [varchar](200) NULL,
  [Remark] [varchar](1000) NULL,
  [SourceSystemAlt_Key] [smallint] NULL,
  [Ischanged] [char](1) NULL,
  [Internal_Rating] [nvarchar](max) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO