CREATE TABLE [dbo].[TempAdvCustRelationship] (
  [EntityKey] [bigint] IDENTITY,
  [CustomerEntityId] [int] NULL,
  [RelationEntityId] [int] NOT NULL,
  [SalutationAlt_Key] [smallint] NULL,
  [Name] [varchar](100) NULL,
  [ConstitutionAlt_Key] [int] NULL,
  [OccupationAlt_Key] [smallint] NULL,
  [ReligionAlt_Key] [smallint] NULL,
  [CasteAlt_Key] [smallint] NULL,
  [FarmerCatAlt_Key] [smallint] NULL,
  [MaritalStatusAlt_Key] [smallint] NULL,
  [NetWorth] [decimal](16, 2) NULL,
  [DateofBirth] [date] NULL,
  [Qualification1Alt_Key] [smallint] NULL,
  [Qualification2Alt_Key] [smallint] NULL,
  [Qualification3Alt_Key] [smallint] NULL,
  [Qualification4Alt_Key] [smallint] NULL,
  [MobileNo] [varchar](21) NULL,
  [Email] [varchar](100) NULL,
  [VoterID] [varchar](30) NULL,
  [RationCardNo] [varchar](20) NULL,
  [AadhaarId] [varchar](20) NULL,
  [NPR_Id] [varchar](20) NULL,
  [PassportNo] [varchar](20) NULL,
  [PassportIssueDt] [date] NULL,
  [PassportExpiryDt] [date] NULL,
  [PassportIssueLocation] [varchar](30) NULL,
  [DL_No] [varchar](20) NULL,
  [DL_IssueDate] [date] NULL,
  [DL_ExpiryDate] [date] NULL,
  [DL_IssueLocation] [varchar](50) NULL,
  [BusiEntity_NationalityTypeAlt_Key] [smallint] NULL,
  [NationalityCountryAlt_Key] [varchar](10) NULL,
  [PAN] [varchar](20) NULL,
  [TAN] [varchar](30) NULL,
  [TIN] [varchar](30) NULL,
  [RegistrationNo] [varchar](30) NULL,
  [DIN] [varchar](20) NULL,
  [CIN] [varchar](21) NULL,
  [ServiceTax] [varchar](30) NULL,
  [OtherID] [varchar](30) NULL,
  [OtherIdType] [varchar](50) NULL,
  [RegistrationAuth] [varchar](30) NULL,
  [RegistrationAuthLocation] [varchar](30) NULL,
  [PrevFinYearSales] [decimal](16, 2) NULL,
  [EmployeeCount] [int] NULL,
  [SalesFigFinYr] [date] NULL,
  [Designation_ContactPeroson] [varchar](30) NULL,
  [IncorporationDate] [date] NULL,
  [BusinessCategoryAlt_Key] [smallint] NULL,
  [BusinessIndustryTypeAlt_Key] [smallint] NULL,
  [SharePercent] [decimal](16, 2) NULL,
  [RetirementDate] [date] NULL,
  [ProfessionArea] [varchar](30) NULL,
  [ExistingCustomer] [char](1) NULL,
  [ScrCrError] [varchar](100) NULL,
  [RefCustomerId] [varchar](20) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](50) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](50) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [CIBILPGId] [varchar](30) NULL,
  [Initial] [varchar](5) NULL,
  [BecomNRI_Dt] [date] NULL,
  [AuthSignStartDt] [date] NULL,
  [AuthSignEndDt] [date] NULL,
  [ScrCrErrorSeq] [varchar](200) NULL,
  [NetWorthDate] [date] NULL,
  [AdvNetWorth] [decimal](16, 2) NULL,
  [DefendentExpire] [char](1) NULL,
  [DefendentExpireDt] [date] NULL,
  [PPhoto] [varbinary](max) NULL,
  [PPhotoDt] [date] NULL,
  [PPhotoURL] [nvarchar](400) NULL,
  [ActionStatus] [varchar](200) NULL,
  [DirectorDebarred] [char](1) NULL,
  [LEI] [varchar](30) NULL,
  [Ischanged] [char](1) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO