CREATE TABLE [dbo].[TempAdvAcBasicDetail] (
  [Ac_Key] [bigint] NULL,
  [BranchCode] [varchar](10) NOT NULL,
  [AccountEntityId] [int] NOT NULL,
  [CustomerEntityId] [int] NOT NULL,
  [SystemACID] [varchar](30) NULL,
  [CustomerACID] [varchar](30) NULL,
  [GLAlt_Key] [int] NULL,
  [ProductAlt_Key] [smallint] NULL,
  [GLProductAlt_Key] [smallint] NULL,
  [FacilityType] [varchar](10) NULL,
  [SectorAlt_Key] [smallint] NULL,
  [SubSectorAlt_Key] [smallint] NULL,
  [ActivityAlt_Key] [smallint] NULL,
  [IndustryAlt_Key] [smallint] NULL,
  [SchemeAlt_Key] [smallint] NULL,
  [DistrictAlt_Key] [smallint] NULL,
  [AreaAlt_Key] [smallint] NULL,
  [VillageAlt_Key] [int] NULL,
  [StateAlt_Key] [smallint] NULL,
  [CurrencyAlt_Key] [smallint] NULL,
  [OriginalSanctionAuthAlt_Key] [smallint] NULL,
  [OriginalLimitRefNo] [varchar](25) NULL,
  [OriginalLimit] [decimal](16, 2) NULL,
  [OriginalLimitDt] [date] NULL,
  [DtofFirstDisb] [date] NULL,
  [FlagReliefWavier] [varchar](1) NULL,
  [UnderLineActivityAlt_Key] [smallint] NULL,
  [MicroCredit] [varchar](1) NULL,
  [segmentcode] [varchar](10) NULL,
  [ScrCrError] [varchar](100) NULL,
  [AdjDt] [date] NULL,
  [AdjReasonAlt_Key] [smallint] NULL,
  [MarginType] [smallint] NULL,
  [Pref_InttRate] [decimal](4, 2) NULL,
  [CurrentLimitRefNo] [varchar](25) NULL,
  [GuaranteeCoverAlt_Key] [smallint] NULL,
  [AccountName] [varchar](80) NULL,
  [AssetClass] [varchar](20) NULL,
  [JointAccount] [varchar](1) NULL,
  [LastDisbDt] [date] NULL,
  [ScrCrErrorBackup] [varchar](100) NULL,
  [AccountOpenDate] [date] NULL,
  [Ac_LADDt] [date] NULL,
  [Ac_DocumentDt] [date] NULL,
  [CurrentLimit] [decimal](16, 2) NULL,
  [InttTypeAlt_Key] [smallint] NULL,
  [InttRateLoadFactor] [decimal](4, 2) NULL,
  [Margin] [decimal](5, 2) NULL,
  [CurrentLimitDt] [date] NULL,
  [Ac_DueDt] [date] NULL,
  [DrawingPowerAlt_Key] [smallint] NULL,
  [RefCustomerId] [varchar](20) NULL,
  [AuthorisationStatus] [char](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [MocStatus] [char](1) NULL,
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [IsLAD] [bit] NULL,
  [FincaleBasedIndustryAlt_key] [smallint] NULL,
  [AcCategoryAlt_Key] [smallint] NULL,
  [OriginalSanctionAuthLevelAlt_Key] [smallint] NULL,
  [AcTypeAlt_Key] [smallint] NULL,
  [ScrCrErrorSeq] [varchar](200) NULL,
  [BSRUNID] [varchar](40) NULL,
  [AdditionalProv] [decimal](16, 2) NULL,
  [AclattestDevelopment] [varchar](1000) NULL,
  [SourceAlt_Key] [tinyint] NULL,
  [LoanSeries] [smallint] NULL,
  [LoanRefNo] [smallint] NULL,
  [SecuritizationCode] [nvarchar](20) NULL,
  [Full_Disb] [char](1) NULL,
  [OriginalBranchcode] [varchar](10) NULL,
  [ProjectCost] [decimal](16, 2) NULL,
  [Ischanged] [char](1) NULL,
  [FlgSecured] [char](1) NULL,
  [ReferencePeriod] [smallint] NULL DEFAULT (90),
  [CountryofExposure] [varchar](50) NULL,
  [Limit_Suffix] [nvarchar](max) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO