CREATE TABLE [dbo].[TempAdvFacDLDetail] (
  [ENTITYKEY] [bigint] NULL,
  [AccountEntityId] [int] NOT NULL,
  [Principal] [decimal](14) NULL,
  [RepayModeAlt_Key] [smallint] NULL,
  [NoOfInstall] [smallint] NULL,
  [InstallAmt] [decimal](14) NULL,
  [FstInstallDt] [date] NULL,
  [LastInstallDt] [date] NULL,
  [Tenure_Months] [smallint] NULL,
  [MarginAmt] [decimal](14) NULL,
  [CommodityAlt_Key] [smallint] NULL,
  [RephaseAlt_Key] [smallint] NULL,
  [RephaseDt] [date] NULL,
  [IntServiced] [char](1) NULL,
  [SuspendedInterest] [decimal](14) NULL,
  [DerecognisedInterest1] [decimal](14) NULL,
  [DerecognisedInterest2] [decimal](14) NULL,
  [AdjReasonAlt_Key] [smallint] NULL,
  [LcNo] [varchar](20) NULL,
  [LcAmt] [decimal](14) NULL,
  [LcIssuingBankAlt_Key] [smallint] NULL,
  [ResetFrequency] [smallint] NULL,
  [ResetDt] [date] NULL,
  [Moratorium] [smallint] NULL,
  [FirstInstallDtInt] [date] NULL,
  [ContExcsSinceDt] [date] NULL,
  [loanPeriod] [int] NULL,
  [ClaimType] [varchar](8) NULL,
  [ClaimCoverAmt] [decimal](14) NULL,
  [ClaimLodgedDt] [date] NULL,
  [ClaimLodgedAmt] [decimal](14) NULL,
  [ClaimRecvDt] [date] NULL,
  [ClaimReceivedAmt] [decimal](14) NULL,
  [ClaimRate] [int] NULL,
  [RefSystemAcid] [varchar](30) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [InstRepaymentDt] [date] NULL,
  [ScrCrError] [varchar](100) NULL,
  [InttRepaymentDt] [date] NULL,
  [ScheDuleNo] [varchar](3) NULL,
  [MocStatus] [char](1) NULL,
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [UnAppliedIntt] [decimal](14) NULL,
  [NxtInstDay] [smallint] NULL,
  [PrplOvduAftrMth] [smallint] NULL,
  [PrplOvduAftrDay] [smallint] NULL,
  [InttOvduAftrDay] [smallint] NULL,
  [InttOvduAftrMth] [smallint] NULL,
  [PrinOvduEndMth] [char](1) NULL,
  [InttOvduEndMth] [char](1) NULL,
  [ScrCrErrorSeq] [varchar](200) NULL,
  [CoverExpiryDt] [date] NULL,
  [Ischanged] [char](1) NULL
)
ON [PRIMARY]
GO