CREATE TABLE [dbo].[TempAdvCustCommunicationDetail] (
  [EntityKey] [bigint] NULL,
  [CustomerEntityId] [int] NULL,
  [RelationEntityId] [int] NULL,
  [RelationAddEntityId] [int] NULL,
  [AddressCategoryAlt_Key] [int] NULL,
  [AddressTypeAlt_Key] [int] NULL,
  [Add1] [varchar](100) NULL,
  [Add2] [varchar](100) NULL,
  [Add3] [varchar](100) NULL,
  [CountryAlt_Key] [smallint] NULL,
  [DistrictAlt_Key] [smallint] NULL,
  [CityAlt_Key] [smallint] NULL,
  [PinCode] [varchar](10) NULL,
  [CustLocationCode] [varchar](16) NULL,
  [STD_Code_Res] [varchar](10) NULL,
  [PhoneNo_Res] [varchar](26) NULL,
  [STD_Code_Off] [varchar](10) NULL,
  [PhoneNo_Off] [varchar](26) NULL,
  [FaxNo] [varchar](26) NULL,
  [ExtensionNo] [varchar](10) NULL,
  [ScrCrError] [varchar](100) NULL,
  [RefCustomerId] [varchar](20) NULL,
  [IsMainAddress] [char](1) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [DUNSNo] [varchar](20) NULL,
  [CIBILPGId] [varchar](30) NULL,
  [CityName] [varchar](60) NULL,
  [ScrCrErrorSeq] [varchar](200) NULL,
  [Ischanged] [char](1) NULL
)
ON [PRIMARY]
GO