CREATE TABLE [dbo].[TempAdvFacNFDetail] (
  [EntityKey] [bigint] NULL,
  [AccountEntityId] [int] NOT NULL,
  [D2KFacilityID] [int] NULL,
  [GLAlt_key] [smallint] NULL,
  [Operative_Acid] [varchar](30) NULL,
  [LCBG_TYPE] [varchar](10) NULL,
  [LCBGNo] [varchar](20) NOT NULL,
  [LcBgAmt] [decimal](16, 2) NULL,
  [OriginDt] [date] NULL,
  [EffectiveDt] [date] NULL,
  [ExpiryDt] [date] NULL,
  [ExtensionDt] [date] NULL,
  [TypeAlt_Key] [smallint] NULL,
  [NatureAlt_Key] [smallint] NULL,
  [BeneficiaryType] [varchar](10) NULL,
  [BeneficiaryName] [varchar](50) NULL,
  [Balance] [decimal](16, 2) NULL,
  [BalanceInCurrency] [decimal](16, 4) NULL,
  [CurrencyAlt_Key] [smallint] NULL,
  [CountryAlt_Key] [smallint] NULL,
  [NegotiatingBank] [varchar](50) NULL,
  [MarginType] [smallint] NULL,
  [MarginAmt] [decimal](14) NULL,
  [PurposeAlt_Key] [smallint] NULL,
  [ShipmentDt] [date] NULL,
  [CoveredByBank] [varchar](50) NULL,
  [CoveredByBankAlt_Key] [smallint] NULL,
  [InvocationDt] [date] NULL,
  [Commission] [decimal](16, 2) NULL,
  [BillReceived] [decimal] NULL,
  [BillsUnderCollAmt] [decimal](20, 4) NULL,
  [FundedConversionDt] [date] NULL,
  [Datepaid] [date] NULL,
  [RecoveryDt] [date] NULL,
  [CounterGuar] [varchar](50) NULL,
  [CorresBankCode] [varchar](10) NULL,
  [CorresBrCode] [varchar](10) NULL,
  [ClaimDt] [date] NULL,
  [NFFacilityNo] [smallint] NULL,
  [Periodicity] [varchar](16) NULL,
  [CommissionDue] [decimal](16, 2) NULL,
  [DueDateOfRecovery] [date] NULL,
  [CommOnDuedateYN] [char](10) NULL,
  [DelayReason] [varchar](75) NULL,
  [PresentPosition] [varchar](75) NULL,
  [AmmountRecovered] [decimal](16, 2) NULL,
  [ScrCrError] [varchar](100) NULL,
  [AdjDt] [date] NULL,
  [AdjReasonAlt_Key] [smallint] NULL,
  [EntityClosureDate] [date] NULL,
  [EntityClosureReasonAlt_Key] [smallint] NULL,
  [RefCustomerId] [varchar](30) NULL,
  [RefSystemAcId] [varchar](30) NULL,
  [AuthorisationStatus] [char](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [MocStatus] [char](1) NULL,
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [GovtGurantee] [varchar](8) NULL,
  [GovGurAmt] [decimal](14) NULL,
  [ScrCrErrorSeq] [varchar](200) NULL,
  [ApplicationDt] [date] NULL,
  [ClaimExpiryDt] [date] NULL,
  [InvocationStatusAlt_Key] [smallint] NULL,
  [provision] [decimal](16, 2) NULL,
  [MarginAccNo] [varchar](16) NULL,
  [IsChanged] [char](1) NULL
)
ON [PRIMARY]
GO