CREATE TABLE [dbo].[TEMPDERVCANCEL_SOURCESYSTEM_BKP_20250407] (
  [DateofData] [date] NULL,
  [SourceSystem] [varchar](30) NULL,
  [BranchCode] [varchar](100) NULL,
  [UCIC_ID] [varchar](30) NULL,
  [CustID] [varchar](50) NULL,
  [CustomerName] [varchar](100) NULL,
  [AcID] [varchar](50) NULL,
  [DerivativeRefNo] [varchar](30) NULL,
  [Duedate] [date] NULL,
  [DueAmt] [decimal](16, 2) NULL,
  [Os_Amt] [decimal](16, 2) NULL,
  [POS] [decimal](16, 2) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](100) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [smalldatetime] NULL,
  [FLGDEG] [char](1) NULL,
  [DEGREASON] [varchar](500) NULL,
  [DPD] [int] NULL,
  [FLGUPG] [char](1) NULL,
  [UpgDate] [date] NULL,
  [DBTDate] [date] NULL,
  [PROVISIONALT_KEY] [int] NULL,
  [InitialAssetAlt_Key] [int] NULL,
  [InitialNPIDt] [date] NULL,
  [DPD_DivOverdue] [int] NULL,
  [FinalAssetClassAlt_Key] [int] NULL,
  [NPIDt] [date] NULL,
  [AssetClass_AltKey] [smallint] NULL,
  [TotalProvison] [decimal](18, 2) NULL,
  [DerivativeEntityID] [int] NULL,
  [MTMIncomeAmt] [decimal](16, 2) NULL,
  [CouponDate] [date] NULL,
  [CouponAmt] [decimal](16, 2) NULL,
  [CouponOverDueSinceDt] [date] NULL,
  [OverdueCouponAmt] [decimal](16, 2) NULL,
  [InstrumentName] [varchar](30) NULL,
  [OverdueSinceDt] [date] NULL
)
ON [PRIMARY]
GO