CREATE TABLE [dbo].[TempBuyoutDetails] (
  [Entity_Key] [bigint] NULL,
  [BuyoutEntityId] [int] NOT NULL,
  [SlNo] [int] NULL,
  [ReferenceNo] [varchar](30) NULL,
  [MainCustomer] [varchar](100) NULL,
  [PoolName] [varchar](50) NULL,
  [Category] [varchar](50) NULL,
  [BuyoutPartyLoanNo] [varchar](20) NULL,
  [CustomerName] [varchar](100) NULL,
  [PAN] [varchar](10) NULL,
  [AadharNo] [varchar](12) NULL,
  [PrincipalOutstanding] [decimal](18, 2) NULL,
  [InterestReceivable] [decimal](18, 2) NULL,
  [Charges] [decimal](18, 2) NULL,
  [AccuredInterest] [decimal](18, 2) NULL,
  [DPD] [int] NULL,
  [AssetClass] [varchar](50) NULL,
  [InterestOverdue] [decimal](16, 2) NULL,
  [NPADate] [date] NULL,
  [SecurityValue] [decimal](16, 2) NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [Changes] [varchar](200) NULL,
  [Remark] [varchar](200) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [date] NULL,
  [ModifyBy] [varchar](100) NULL,
  [DateModified] [date] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [date] NULL,
  [DailyInterestAccrualAmount] [decimal](16, 2) NULL,
  [InterestSuspendedAmount] [decimal](16, 2) NULL,
  [SuspendedInterestAmount] [decimal](16, 2) NULL,
  [IsChanged] [char](1) NULL
)
ON [PRIMARY]
GO