CREATE TABLE [dbo].[TempInvestmentBasicDetail] (
  [BranchCode] [varchar](100) NULL,
  [Inv_Key] [tinyint] NULL,
  [InvID] [varchar](100) NULL,
  [IssuerID] [varchar](30) NULL,
  [ISIN] [varchar](100) NULL,
  [InstrTypeAlt_Key] [tinyint] NULL,
  [InstrName] [varchar](100) NULL,
  [InvestmentNature] [varchar](25) NULL,
  [InternalRating] [tinyint] NULL,
  [InRatingDate] [date] NULL,
  [InRatingExpiryDate] [date] NULL,
  [ExRating] [tinyint] NULL,
  [ExRatingAgency] [tinyint] NULL,
  [ExRatingDate] [date] NULL,
  [ExRatingExpiryDate] [date] NULL,
  [Sector] [varchar](25) NULL,
  [Industry_AltKey] [tinyint] NULL,
  [ListedStkExchange] [char](1) NULL,
  [ExposureType] [varchar](25) NULL,
  [SecurityValue] [decimal](18, 2) NULL,
  [MaturityDt] [date] NULL,
  [ReStructureDate] [date] NULL,
  [MortgageStatus] [char](1) NULL,
  [NHBStatus] [char](1) NULL,
  [ResiPurpose] [char](1) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](100) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [smalldatetime] NULL,
  [Ischanged] [char](1) NULL,
  [InvEntityId] [int] NULL,
  [issuerEntityid] [int] NULL,
  [EntityKey] [bigint] NULL
)
ON [PRIMARY]
GO