CREATE TABLE [dbo].[TempAdvFacPCDetail_BKP_20250407] (
  [EntityKey] [bigint] NOT NULL,
  [AccountEntityId] [int] NOT NULL,
  [PCRefNo] [varchar](20) NOT NULL,
  [PCAdvDt] [date] NULL,
  [PCAmt] [decimal](16, 2) NULL,
  [PCDueDt] [date] NULL,
  [PCDurationDays] [smallint] NULL,
  [PCExtendedDueDt] [date] NULL,
  [ExtensionReason] [varchar](50) NULL,
  [CurrencyAlt_Key] [smallint] NULL,
  [LcNo] [varchar](20) NULL,
  [LcAmt] [decimal](14) NULL,
  [LcIssueDt] [date] NULL,
  [LcIssuingBank_FirmOrder] [varchar](50) NULL,
  [Balance] [decimal](16, 2) NULL,
  [BalanceInCurrency] [decimal](16, 4) NULL,
  [BalanceInUSD] [decimal](16, 4) NULL,
  [Overdue] [decimal](14) NULL,
  [CommodityAlt_Key] [smallint] NULL,
  [CommodityValue] [decimal](14) NULL,
  [CommodityMarketValue] [decimal](14) NULL,
  [ShipmentDt] [date] NULL,
  [CommercialisationDt] [date] NULL,
  [EcgcPolicyNo] [varchar](20) NULL,
  [CAD] [decimal](14) NULL,
  [CADU] [decimal](14) NULL,
  [OverDueSinceDt] [date] NULL,
  [TotalProv] [decimal](14) NULL,
  [Secured] [decimal](14) NULL,
  [Unsecured] [decimal](14) NULL,
  [Provsecured] [decimal](14) NULL,
  [ProvUnsecured] [decimal](14) NULL,
  [ProvDicgc] [decimal](14) NULL,
  [npadt] [date] NULL,
  [CoverGovGur] [decimal](16, 2) NULL,
  [DerecognisedInterest1] [decimal](14) NULL,
  [DerecognisedInterest2] [decimal](14) NULL,
  [ClaimType] [varchar](8) NULL,
  [ClaimCoverAmt] [decimal](14) NULL,
  [ClaimLodgedDt] [date] NULL,
  [ClaimLodgedAmt] [decimal](14) NULL,
  [ClaimRecvDt] [date] NULL,
  [ClaimReceivedAmt] [decimal](14) NULL,
  [ClaimRate] [decimal](4, 2) NULL,
  [AdjDt] [date] NULL,
  [EntityClosureDate] [date] NULL,
  [EntityClosureReasonAlt_Key] [smallint] NULL,
  [RefSystemAcid] [varchar](30) NULL,
  [AuthorisationStatus] [char](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [datetime] NULL,
  [UnAppliedIntt] [decimal](14, 2) NULL,
  [MocTypeAlt_Key] [smallint] NULL,
  [MocStatus] [char](1) NULL,
  [MocDate] [smalldatetime] NULL,
  [RBI_ExtnPermRefNo] [varchar](25) NULL,
  [LC_OrderAlt_Key] [smallint] NULL,
  [OrderLC_CurrencyAlt_Key] [smallint] NULL,
  [CountryAlt_Key] [smallint] NULL,
  [LcAmtInCurrenc] [decimal](16, 4) NULL,
  [PcEntityId] [int] NULL,
  [Ischanged] [char](1) NULL
)
ON [PRIMARY]
GO