CREATE TABLE [dbo].[TempAdvNFAcBasicDetail] (
  [Ac_Key] [bigint] NULL,
  [BranchCode] [varchar](10) NULL,
  [CustomerEntityId] [int] NULL,
  [AccountEntityId] [int] NOT NULL,
  [SystemACID] [varchar](30) NULL,
  [CustomerACID] [varchar](30) NULL,
  [D2KAcid] [varchar](30) NULL,
  [ProductAlt_Key] [smallint] NULL,
  [GLProductAlt_Key] [smallint] NULL,
  [FacilityType] [varchar](10) NULL,
  [SectorAlt_Key] [smallint] NULL,
  [SubSectorAlt_Key] [smallint] NULL,
  [ActivityAlt_Key] [smallint] NULL,
  [IndustryAlt_Key] [smallint] NULL,
  [DistrictAlt_Key] [smallint] NULL,
  [AreaAlt_Key] [smallint] NULL,
  [StateAlt_Key] [smallint] NULL,
  [CurrencyAlt_Key] [smallint] NULL,
  [OriginalSanctionAuthAlt_Key] [smallint] NULL,
  [OriginalLimitRefNo] [varchar](25) NULL,
  [OriginalLimit] [decimal](16, 2) NULL,
  [OriginalLimitDt] [date] NULL,
  [DtofFirstDisb] [date] NULL,
  [ScrCrError] [varchar](100) NULL,
  [AdjDt] [date] NULL,
  [AdjReasonAlt_Key] [smallint] NULL,
  [VillageCode] [int] NULL,
  [SplCatg1Alt_Key] [smallint] NULL,
  [SplCatg2Alt_Key] [smallint] NULL,
  [CreditRatingScore] [int] NULL,
  [CreditRatingDt] [date] NULL,
  [SanctionReferenceNo] [varchar](20) NULL,
  [GuaranteeCoverAlt_Key] [smallint] NULL,
  [JointAccount] [varchar](1) NULL,
  [ProcessingFeeApplicable] [varchar](1) NULL,
  [ProcessingFeeAmt] [decimal](16, 2) NULL,
  [ProcessingFeeRecoveryAmt] [decimal](16, 2) NULL,
  [LimitRefNo] [varchar](20) NULL,
  [Ac_LADDt] [date] NULL,
  [Ac_DocumentDt] [date] NULL,
  [Ac_CreditRatingAlt_Key] [smallint] NULL,
  [CurrentLimit] [decimal](16, 2) NULL,
  [CurrentLimitDt] [date] NULL,
  [AccountOpenDate] [date] NULL,
  [EmpCode] [varchar](6) NULL,
  [CurrentLimitRefNo] [varchar](25) NULL,
  [MarginType] [smallint] NULL,
  [Margin] [decimal](5, 2) NULL,
  [RefCustomerID] [varchar](20) NULL,
  [AuthorisationStatus] [char](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [MocStatus] [char](1) NULL,
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [SplCatg3Alt_Key] [smallint] NULL,
  [SplCatg4Alt_Key] [smallint] NULL,
  [NonFundCategoryAlt_Key] [smallint] NULL,
  [FacilitiesNo] [smallint] NULL,
  [BankAlt_Key] [smallint] NULL,
  [AcCategoryAlt_Key] [smallint] NULL,
  [OriginalSanctionAuthLevelAlt_Key] [smallint] NULL,
  [AcTypeAlt_Key] [smallint] NULL,
  [ScrCrErrorSeq] [varchar](200) NULL,
  [Old_Mapkey] [varchar](30) NULL,
  [D2k_OLDAscromID] [varchar](20) NULL,
  [BSRUNID] [varchar](40) NULL,
  [CustomerId] [varchar](20) NULL,
  [CustomerName] [varchar](80) NULL,
  [IsChanged] [char](1) NULL,
  [segmentcode] [varchar](10) NULL,
  [SourceAlt_Key] [tinyint] NULL
)
ON [PRIMARY]
GO